name: PR Validation

on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: pr-validation-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:

    name: PR Validation Pipeline

    runs-on: self-hosted

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
